services:
  db:
    image: postgres:16
    container_name: helpdesk-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk
      POSTGRES_DB: helpdesk
    volumes:
      - helpdesk_pg:/var/lib/postgresql/data

volumes:
  helpdesk_pg:
